#机器人功能设置
Ver: "1.3.3"

#QQ群聊命令前缀
Prefix: "/"

#消息转发
Forwarding:
  enable: true
  mode: 0 #mode设为0即无条件转发消息，设为1则消息前有前缀才会转发消息
  prefix: "#"

#死亡报告
DieReport: false

#白名单
WhiteList:
  enable: false
  kickMsg: "请加入qq群:xxx申请白名单"
  maxCount: 1

#执行命令功能
CMD: true

#进出提示
JoinAndLeave: true

#在线玩家查询
Online: true

#tps查询
TPS: true

#自定义命令
SDC: true

#自定义回复
SDR: true

#maven仓库地址，默认为官方仓库，如速度慢或下载失败可更换为镜像仓库
#此值为空时默认使用官方仓库
Maven: "https://repo1.maven.org/maven2"

database:
  type: sqlite
  settings:
    sqlite:
      path: "%plugin_folder%/database.db"
    mysql:
      host: localhost
      port: 3306
      database: plumbot
      user: plumbot
      password: plumbot
      parameters: "?useSSL=false"
    pool:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 15
      keepaliveTime: 0
      minimumIdle: 5
      #当服务端出现类似
      #“Receiver class org.sqlite.Conn does not define or
      # inherit an implementation of the resolved method 'abstract boolean isValid(int)'
      # of interface java.sql.Connection.”
      #报错时，将下面配置取消注释
      #connectionTestQuery: "SELECT 1"