#机器人功能设置
Ver: "2.0.0"

#语言文件在lang文件夹里
lang: "zh_CN"
#群聊命令前缀
commandPrefix: "/"
#消息转发
forwarding:
  enable: true
  mode: 0 #mode设为0即无条件转发消息，设为1则消息前有前缀才会转发消息
  prefix: "#"
#死亡报告
dieReport: false
#白名单
whiteList:
  enable: false
  maxCount: 1
#执行命令功能
cmd: true
#进出提示
joinAndLeave: true
#在线玩家查询
online: true
#tps查询
tps: true
#自定义命令
SDC: true
#自定义回复
SDR: true

database:
  type: sqlite
  settings:
    sqlite:
      path: "%plugin_folder%/database.db"
    mysql:
      host: localhost
      port: 3306
      database: plumbot
      user: plumbot
      password: plumbot
      flagsURL: "?useSSL=false"
    pool:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 15
      keepaliveTime: 0
      minimumIdle: 5
      #当服务端出现类似
      #“Receiver class org.sqlite.Conn does not define or
      # inherit an implementation of the resolved method 'abstract boolean isValid(int)'
      # of interface java.sql.Connection.”
      #报错时，将下面配置取消注释
      #connectionTestQuery: "SELECT 1"

enableGroups:
  - 111
  #启用消息转发功能的群聊Id

botAdmins:
  - 111
  #管理员的userId

bot:
  mode: "kook"
  #机器人模式，可选go-cqhttp、kook
  go-cqhttp:
    ws: "ws://127.0.0.1:3001"
    #go-cqhttp的config文件中正向ws模式
    token: ""
    #go-cqhttp是否开启了access-token模式，如是，请填写，如否，则该项无效
    hasAccessToken: false
    #go-cqhttp是否开启了access-token模式
  kook:
    #kook机器人，只支持websocket
    token: ""
    #kook机器人Token